version: '3.9-slim'
services:
  redis:
    image: redis:alpine

    volumes:
      - redis_data:/data

    ports:
      - "6379:6379"

  postgres:

    image: postgres:16

    env_file:
      - .env

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:

#  web:
#    build: .
#    depends_on:
#      - redis
#      - postgres
#    ports:
#      - "8000:8000"
#    environment:
#      DATABASE_URL: ${DB_URL}
#      SECRET_KEY_JWT: ${SECRET_KEY_JWT}
#      ALGORITHM: ${ALGORITHM}
#      MAIL_USERNAME: ${MAIL_USERNAME}
#      MAIL_PASSWORD: ${MAIL_PASSWORD}
#      MAIL_FROM: ${MAIL_FROM}
#      MAIL_PORT: ${MAIL_PORT}
#      MAIL_SERVER: ${MAIL_SERVER}
#      REDIS_DOMAIN: ${REDIS_DOMAIN}
#      REDIS_PORT: ${REDIS_PORT}
#      REDIS_PASSWORD: ${REDIS_PASSWORD}
